title: Adaptive Real Time Machine Learning
description: A blog on Adaptive real time Machine learning technique

url: https://sundeeppothula1993.github.io/ARTML/
baseurl: "/ARTML/"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: sundeeppothula1993
   twitter: 
   facebook: 
   email: sundeeppothula@gmail.com

google_analytics: "UA-58263416-1"

plugins: 
        - jekyll-sitemap
